name: cd
run-name: CD

on:
  push:
    branches:
      - main

jobs:
  run-test:
    uses: ./.github/workflows/test.yaml
    secrets: inherit

  run-deploy:
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
